#nowe,nowenmwoe w
name: Push to Azure Container Registry
on:
  push:
    branches:
      - main

jobs:
  push-to-azure-container-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
#          creds: ${{  secrets.AZURE_CREDENTIALS }}
          login-server: ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZ_SP_CLIENT_ID }}
          password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

      - name: Build Docker image
        run: docker build --build-arg MISP_VERSION=v2.4.152 -t ghcr.io/nukib/misp https://github.com/NUKIB/misp.git#main
#        run: docker-compose build
#        run: docker-compose up -d mydemoapp
#        run: docker-compose up -d --build
#       run: docker-compose -f "docker-compose.yml" up -d --build
      - name: docker image
        run: docker images

      - name: Push Docker image to Azure Container Registry
        run: |
            docker push ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/misp-modules
#            docker tag mydemoapp:latest ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/mydemoapp:${{ github.sha }}
#            docker push ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/mydemoapp:${{ github.sha }}
            
            
            
